### ISSUE TITLE
Problems with finding bin/web3j on path

### ISSUE THREAD

**Issue by kincsescsaba** [mslinn/web3j-scala#21]
I'm testing in a Linux environment. I already copied the files under bin a bin folder in my project so that the script can find build.sbt.
I figured out that it only finds the web3j script if I pass it as "web3j" instead of "bin/web3j".
Another problem is that the program does not read the per user PATH but some global PATH instead. If I create a symlink under /usr/local/bin pointing to the bin directory in the project then it does not find build.sbt as it searches it at /usr/local.
Why would I add a single project to the global PATH? What if I want to use different versions of your scripts in two or more different projects, then how would I add the scripts to the PATH so that the program can find it?
Won't it be easier to provide some configurable variables for setting where to search for those scripts instead of messing with PATH and run them with an explicit path like /path/to/bin/scripts/./web3j ?

**Comment by mslinn** [comment]
I addressed the information you provided. You did not mention an error.

**Comment by kincsescsaba** [comment]
This line is run in Cmd.scala: case None => sys.error(program + " not found on PATH")
It displays "bin/web3j not found on PATH" when I run wrapAbi. I copied wrapAbi, tried to fix PATH, but this message only disappeared when I ran it as "web3j" instead of "bin/web3j".

**Comment by kincsescsaba** [comment]
Don't know if it's a bug, firstly I would need to understand clearly why the code is written as is. For example why is it important to do that PATH check.

**Comment by mslinn** [comment]
What happens if you set this definition before running the program?

    PATH="./bin:$PATH"

**Comment by kincsescsaba** [comment]
Tried, still not working. I added web3j-scala as a dependency to my SBT project, I'm trying to run a test. I do not call the scripts in bin directly, the def wrapAbi tries to call bin/web3j.

I have an idea how to fix this, I would remove enforcing the script to be in PATH. 

Don't know if this is a good idea as I don't know what were the considerations behind enforcing it to be in PATH

**Comment by kincsescsaba** [comment]
I added some lines to Cmd.scala:which, now it works fine
`protected def which(program: String): Option[Path] = {
    val path = if (isWindows) sys.env("Path") else sys.env("PATH")
    path
      .split(Pattern.quote(File.pathSeparator))
      .map(Paths.get(_))
      .find(path => Files.exists(path.resolve(program)))
      .map(_.resolve(program)).orElse(
        Paths.get("").resolve(program) match {
          case path if Files.exists(path) => Some(path)
          case _ => None
        }
    )
  }`

**Comment by mslinn** [comment]
If this fixes your problem, and you feel it is generally useful, please write up a PR

**Comment by kincsescsaba** [comment]
Ok
